### ISSUE TITLE
Update core gems

### ISSUE THREAD

**Issue by jmarrec** [jmarrec/OpenStudio-update-gems#1]
* [ ] OpenStudio-measure-tester-gem
    * [x] PR Ready to drop: https://github.com/NREL/OpenStudio-measure-tester-gem/pull/42
    * [ ] PR Merged
    * [ ] Re-release **0.20.0**

* [ ] openstudio-extension-gem 
    * [x] PR Ready to drop: https://github.com/NREL/openstudio-extension-gem/pull/54/
    * **REVIEW COMMENTS LEFT**, especially version constraint with pre-release tag
    * [ ] PR Merged
    * [ ] Release **0.20.0**

* [ ] openstudio-standards
    * [x] PR Ready to drop: https://github.com/NREL/openstudio-standards/pull/797
    * *NOTE: This PR is optional*, it doesn't have any incompability in `add_dependency` (it uses `add_development_dependency`)
    * [ ] PR Merged
    * [ ] Release **0.2.11.rc1**

* [ ] openstudio-gems: the ring to rule them all
    * [x] PR Ready to drop: https://github.com/NREL/openstudio-gems/pull/18
    * [ ] PR Merged
    * [ ] Release uneeded.
    * [x] Launch a test package with this @tijcolem?

**Comment by jmarrec** [comment]
@nllong and @tijcolem I opened the PRs on the core gem repos, ready to review/merge/release.

**Comment by nllong** [comment]
@jmarrec -- can I get write access to this repo so I can update your punch list?

**Comment by nllong** [comment]
- [x] OpenStudio-measure-tester-gem
  - [x] PR Ready to drop: NREL/OpenStudio-measure-tester-gem#42
  - [x] PR Merged
  - [x] Release 0.2.1

- [x] openstudio-workflow
  - [x] Release 2.0.0

- [x] openstudio-extension-gem
  - [x] Update OpenStudio Measure Tester version
  - [x] PR Ready to drop: NREL/openstudio-extension-gem#54
  - [x] REVIEW COMMENTS LEFT, especially version constraint with pre-release tag
  - [x] PR Merged
  - [x] Release 0.2.1

- [ ] openstudio-standards
  - [ ] PR Ready to drop: NREL/openstudio-standards#797
  - [ ] NOTE: This PR is optional, it doesn't have any incompatibility in add_dependency (it uses add_development_dependency)
  - [ ] PR Merged
  - [ ] Release 0.2.11.rc1

- [ ] openstudio-gems: the ring to rule them all
  - [x] Update versions based on the above releases
  - [ ] PR Ready to drop: https://github.com/NREL/openstudio-gems/pull/23
  - [ ] PR Merged
  - [ ] Release unneeded.
  - [ ] Launch a test package with this @tijcolem?

**Comment by jmarrec** [comment]
> @jmarrec -- can I get write access to this repo so I can update your punch list?

You're still showing as "Pending invite": https://github.com/jmarrec/OpenStudio-update-gems/invitations

**Comment by nllong** [comment]
> > @jmarrec -- can I get write access to this repo so I can update your punch list?
> 
> You're still showing as "Pending invite": https://github.com/jmarrec/OpenStudio-update-gems/invitations

I accepted the invite. Still can't edit your comment. Had to recreate and edit my own version (above)
